---
title: "EDLD_651_Final_Project"
format: html
editor: visual
author: "xxxx"
---

# Load packages

```{r}
library(tidyverse)
library(psych)       # For descriptive statistics
library(car)         # For assumption testing
library(lmtest)      # For regression diagnostics
library(ggplot2)     # For visualization
library(interactions) # For moderation analysis
library(flextable) # For APA style tables
library(jtools)        # APA-style visualization
library(ggpubr)        # For arranging multiple plots
library(broom)
library(here)
library(readr)
library(readxl)
library(stringr)
```

# Load data

```{r}
# Demographic
Age <- read_csv(here("data", "TAG_age_session_dates_4waves.csv"))
Race <- read_excel(here("data", "TAG_W1_Race_Ethnicity.xlsx"))

# Emotion Regulation(ERQ)
ERQ <- read_csv(here("data", "ERQ_Wave1.csv"))

# Adolescent Depression(CESDC)
CESDC <- read_csv(here("data", "CESDC_Wave1.csv"))

```

# Participant demographic

```{r}
# Race/ethnicity category
# Clean the data frame: identify subjects reported multiple racial categories and rename them to "Multi-racial"
Race_clean <- Race %>%
  mutate(
    W1_Ethnicity = as.character(W1_Ethnicity),

    # recode if the cell contains more than one category
    W1_Ethnicity = if_else(
      str_detect(W1_Ethnicity, ","),   # contains ,
      "g.Multi-racial",
      W1_Ethnicity
    )
  )

# Average age between session 1 & 2
## We have subject age data at both sessions and we are interested in calculating the mean age of the two sessions of wave1. 
W1_mean_age <- Age %>% 
  mutate(W1_mean_age = (w1s1_age + w1s2_age)/2)

# Report demographic statistics
## Combine W1_ethnicity and W1_mean_age and report the descriptive statistics in APA style table


```

# Consolidata data frame to answer the research questions
```{r}
# Select and combine ERQ_reappraisal_total, ERQ_suppression-total, CES_DC_total_75perc: 
df <- CESDC %>% 
  left_join(ERQ, by= 'tagid') %>%
  select('tagid', 'CES_DC_total_75perc', 'ERQ_reappraisal_total', 'ERQ_suppression_total')

```


# RQ 1
## Does emotion repraissal predict adolescent depression symptoms?

```{r}
model1 <- lm(df$CES_DC_total_75perc ~ df$ERQ_reappraisal_total)
summary(model1)

```

# RQ 2
## Does emotion suppression predict adolescent depression symptoms?

```{r}
model2 <- lm(df$CES_DC_total_75perc ~ df$ERQ_suppression_total)
summary(model2)

```
# Multiple regression analysis for depression - ERQ
```{r}
model3 <- lm(df$CES_DC_total_75perc ~ df$ERQ_reappraisal_total + df$ERQ_suppression_total)
summary(model3)

```



# Resutl report (table/plot)
```{r}

```

# Discussion



